version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" 
    environment:
      - SERVICES=lambda,s3,iam
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - DATA_DIR=/var/lib/localstack
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

