version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" 
    environment:
      - SERVICES=lambda,s3,iam
      - DEBUG=1
      - LAMBDA_EXECUTOR=local  # Use 'local' executor for consistency
      - DATA_DIR=/var/lib/localstack
    volumes:
      - "./.localstack:/var/lib/localstack"
    # Remove Docker socket mount as it's not needed with LAMBDA_EXECUTOR=local
