name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: lambda,s3,iam
          DEBUG: 1
          LAMBDA_EXECUTOR: local  # Use 'local' executor
          DATA_DIR: /tmp/localstack/data
        options: >-
          --name localstack
          --health-cmd "curl -f http://localhost:4566/health || exit 1"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 20
          --cpus 0.5
          --memory 1g
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Wait for LocalStack to be ready
        run: |
          echo "Waiting for LocalStack to be ready..."
          until curl -s http://localstack:4566/health | grep "\"services\": {"; do
            sleep 5
          done
          echo "LocalStack is ready."

      - name: Apply Terraform configuration
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          pytest tests/

      - name: Clean up
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          terraform destroy -auto-approve

      - name: Dump LocalStack logs on failure
        if: failure()
        run: |
          echo "LocalStack container logs:"
          docker logs localstack
